#
# Site configuration
# 

title: Ashleigh Wilson's Blog
email: ashleigh.wilson85@icloud.com
description: >- 
  A place to document my interests.
baseurl: ""
url: ""
# twitter_username: todo
github_username:  AshleighWilson

permalink: /article/:title

#
# Build settings
#

plugins:
  - jekyll-feed
