#
# Site configuration
# 

title: Ashleigh Wilson's Blog
email: ashleigh.wilson85@icloud.com
description: >- 
  A place to document my interests.
baseurl: ""
url: ""
keywords: ["blog", "engineering"]
# twitter_username: todo
github_username:  AshleighWilson

permalink: /articles/:title

#
# Build settings
#

plugins:
  - jekyll-feed

owner:
  name: Ashleigh Wilson
  job: "Engineer"
  bio: "Interested in interesting things"
  avatar: "avatar.png"
  # email: add-email
  # twitter: username
  # facebook: username
  linkedin: ashleigh-wilson85
  # instagram: username
  github: ashleighwilson
  # stackoverflow: username
  # youtube: username
  # reddit: username.
  google:
    analytics: UA-156063991-1
  
